package ElectoresApp;


/**
* ElectoresApp/_ElectoresStub.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electores.idl
* jueves 24 de mayo de 2018 12:55:09 AM COT
*/

public class _ElectoresStub extends org.omg.CORBA.portable.ObjectImpl implements ElectoresApp.Electores
{

  public boolean insertarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("insertarElectores", true);
                $out.write_long (EL_ID);
                $out.write_wstring (EL_NOMBRE);
                $out.write_wstring (EL_CANDIDATO);
                $out.write_wstring (EL_PARTIDO);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return insertarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO        );
            } finally {
                _releaseReply ($in);
            }
  } // insertarElectores

  public String consultarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("consultarElectores", true);
                $out.write_long (EL_ID);
                $out.write_wstring (EL_NOMBRE);
                $out.write_wstring (EL_CANDIDATO);
                $out.write_wstring (EL_PARTIDO);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return consultarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO        );
            } finally {
                _releaseReply ($in);
            }
  } // consultarElectores

  public boolean eliminarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("eliminarElectores", true);
                $out.write_long (EL_ID);
                $out.write_wstring (EL_NOMBRE);
                $out.write_wstring (EL_CANDIDATO);
                $out.write_wstring (EL_PARTIDO);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return eliminarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO        );
            } finally {
                _releaseReply ($in);
            }
  } // eliminarElectores

  public boolean actualizarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO)
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("actualizarElectores", true);
                $out.write_long (EL_ID);
                $out.write_wstring (EL_NOMBRE);
                $out.write_wstring (EL_CANDIDATO);
                $out.write_wstring (EL_PARTIDO);
                $in = _invoke ($out);
                boolean $result = $in.read_boolean ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return actualizarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO        );
            } finally {
                _releaseReply ($in);
            }
  } // actualizarElectores

  public String listarElectores ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("listarElectores", true);
                $in = _invoke ($out);
                String $result = $in.read_wstring ();
                return $result;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                return listarElectores (        );
            } finally {
                _releaseReply ($in);
            }
  } // listarElectores

  public void shutdown ()
  {
            org.omg.CORBA.portable.InputStream $in = null;
            try {
                org.omg.CORBA.portable.OutputStream $out = _request ("shutdown", false);
                $in = _invoke ($out);
                return;
            } catch (org.omg.CORBA.portable.ApplicationException $ex) {
                $in = $ex.getInputStream ();
                String _id = $ex.getId ();
                throw new org.omg.CORBA.MARSHAL (_id);
            } catch (org.omg.CORBA.portable.RemarshalException $rm) {
                shutdown (        );
            } finally {
                _releaseReply ($in);
            }
  } // shutdown

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ElectoresApp/Electores:1.0"};

  public String[] _ids ()
  {
    return (String[])__ids.clone ();
  }

  private void readObject (java.io.ObjectInputStream s) throws java.io.IOException
  {
     String str = s.readUTF ();
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     org.omg.CORBA.Object obj = orb.string_to_object (str);
     org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl) obj)._get_delegate ();
     _set_delegate (delegate);
   } finally {
     orb.destroy() ;
   }
  }

  private void writeObject (java.io.ObjectOutputStream s) throws java.io.IOException
  {
     String[] args = null;
     java.util.Properties props = null;
     org.omg.CORBA.ORB orb = org.omg.CORBA.ORB.init (args, props);
   try {
     String str = orb.object_to_string (this);
     s.writeUTF (str);
   } finally {
     orb.destroy() ;
   }
  }
} // class _ElectoresStub
