package ElectoresApp;


/**
* ElectoresApp/ElectoresPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electores.idl
* jueves 24 de mayo de 2018 12:55:09 AM COT
*/

public abstract class ElectoresPOA extends org.omg.PortableServer.Servant
 implements ElectoresApp.ElectoresOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("insertarElectores", new java.lang.Integer (0));
    _methods.put ("consultarElectores", new java.lang.Integer (1));
    _methods.put ("eliminarElectores", new java.lang.Integer (2));
    _methods.put ("actualizarElectores", new java.lang.Integer (3));
    _methods.put ("listarElectores", new java.lang.Integer (4));
    _methods.put ("shutdown", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // ElectoresApp/Electores/insertarElectores
       {
         int EL_ID = in.read_long ();
         String EL_NOMBRE = in.read_wstring ();
         String EL_CANDIDATO = in.read_wstring ();
         String EL_PARTIDO = in.read_wstring ();
         boolean $result = false;
         $result = this.insertarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 1:  // ElectoresApp/Electores/consultarElectores
       {
         int EL_ID = in.read_long ();
         String EL_NOMBRE = in.read_wstring ();
         String EL_CANDIDATO = in.read_wstring ();
         String EL_PARTIDO = in.read_wstring ();
         String $result = null;
         $result = this.consultarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO);
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 2:  // ElectoresApp/Electores/eliminarElectores
       {
         int EL_ID = in.read_long ();
         String EL_NOMBRE = in.read_wstring ();
         String EL_CANDIDATO = in.read_wstring ();
         String EL_PARTIDO = in.read_wstring ();
         boolean $result = false;
         $result = this.eliminarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 3:  // ElectoresApp/Electores/actualizarElectores
       {
         int EL_ID = in.read_long ();
         String EL_NOMBRE = in.read_wstring ();
         String EL_CANDIDATO = in.read_wstring ();
         String EL_PARTIDO = in.read_wstring ();
         boolean $result = false;
         $result = this.actualizarElectores (EL_ID, EL_NOMBRE, EL_CANDIDATO, EL_PARTIDO);
         out = $rh.createReply();
         out.write_boolean ($result);
         break;
       }

       case 4:  // ElectoresApp/Electores/listarElectores
       {
         String $result = null;
         $result = this.listarElectores ();
         out = $rh.createReply();
         out.write_wstring ($result);
         break;
       }

       case 5:  // ElectoresApp/Electores/shutdown
       {
         this.shutdown ();
         out = $rh.createReply();
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:ElectoresApp/Electores:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public Electores _this() 
  {
    return ElectoresHelper.narrow(
    super._this_object());
  }

  public Electores _this(org.omg.CORBA.ORB orb) 
  {
    return ElectoresHelper.narrow(
    super._this_object(orb));
  }


} // class ElectoresPOA
