package ElectoresApp;

/**
* ElectoresApp/ElectoresHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electores.idl
* jueves 17 de mayo de 2018 11:57:33 AM COT
*/

public final class ElectoresHolder implements org.omg.CORBA.portable.Streamable
{
  public ElectoresApp.Electores value = null;

  public ElectoresHolder ()
  {
  }

  public ElectoresHolder (ElectoresApp.Electores initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ElectoresApp.ElectoresHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ElectoresApp.ElectoresHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ElectoresApp.ElectoresHelper.type ();
  }

}
