package ElectoresApp;


/**
* ElectoresApp/Electores.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electores.idl
* jueves 17 de mayo de 2018 11:57:33 AM COT
*/

public interface Electores extends ElectoresOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface Electores
