package ElectoresApp;


/**
* ElectoresApp/ElectoresOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Electores.idl
* jueves 24 de mayo de 2018 12:55:09 AM COT
*/

public interface ElectoresOperations 
{
  boolean insertarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO);
  String consultarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO);
  boolean eliminarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO);
  boolean actualizarElectores (int EL_ID, String EL_NOMBRE, String EL_CANDIDATO, String EL_PARTIDO);
  String listarElectores ();
  void shutdown ();
} // interface ElectoresOperations
